### ISSUE TITLE
Allow basic keyboard controls of merge tags

### ISSUE THREAD

**Issue by xhocquet** [rob-race/react-trix#13]
Hi there!

One small improvement to the merge tags would be to allow the user to press UP and DOWN to navigate the options, and ENTER to select. Otherwise, the user is required to move their hands from the keyboard while typing.

I wanted to offer the idea for you to implement since its your project, but I'll happily open a PR for it! I'll be needing the functionality shortly so I'll share the love!

**Comment by xhocquet** [comment]
cc @dstpierre

**Comment by dstpierre** [comment]
sure @xhocquet please go ahead with a PR if you have time.

I'm having difficulties reserving some work hour for this project at this moment.
